[package]
name = "battleship"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]


[dependencies]
rand = "0.8.5"
nalgebra = "0.31.2"
rayon = "1.5.3"
